### ISSUE TITLE
Is_mac does not work

### ISSUE THREAD

**Issue by dragonito** [rage311/ocss#2]
Hi,

the is_mac as function does not really work, it always uses the "linux"-case. Perhaps you have an idea to make it work. I could test it for you, if you dont have a mac system.

Cu

Robin

**Comment by dragonito** [comment]
Perhaps its not the problem of the function, in line 87 i tries to use scrot wich is not available on mac

**Comment by rage311** [comment]
Is there a specific issue you're having?

Can you try running the script in a terminal to see if you get any useful debugging output for said issue?

Line 87:
`if ! (scrot -s "$1" || screencapture -s "$1"); then #takes a screenshot with selection`
uses the two pipes which is an "or".  The call to `scrot` will fail if it doesn't exist on your system, and at that point it will run `screencapture` instead.  I've tested this on Linux and FreeBSD both as is and with reversing the order of the commands to ensure the fallback command execution works, which it does on both of those OSes.

I need more details in order to help you resolve whatever issue you're having.  I know your previously-filed issue included a snippet using `gnome-screenshot`, which must have been your addition or part of one of the forks of my project, so please ensure you're using my `ocss.sh` script as it exists in the github repo, or it's pointless for me to try to help resolve it.
